stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  SERVER_IMAGE: $CI_REGISTRY_IMAGE/real-estate-server
  DASHBOARD_IMAGE: $CI_REGISTRY_IMAGE/real-estate-dashboard

build_server:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd real-estate-server
    - docker build -t $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA $SERVER_IMAGE:latest
    - docker push $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $SERVER_IMAGE:latest

build_dashboard:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd real-estate-dashboard
  script:
    - docker build -t $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA $DASHBOARD_IMAGE:latest
    - docker push $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DASHBOARD_IMAGE:latest

deploy:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  environment:
    name: production
    url: https://93.127.203.195
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh haythem@93.127.203.195 "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
    - ssh haythem@93.127.203.195 "docker pull $SERVER_IMAGE:latest"
    - ssh haythem@93.127.203.195 "docker pull $DASHBOARD_IMAGE:latest"
    - scp compose.prod.yml haythem@93.127.203.195:/home/haythem/
    - ssh haythem@93.127.203.195 "
            export SERVER_IMAGE=\"$SERVER_IMAGE\" &&
            export DASHBOARD_IMAGE=\"$DASHBOARD_IMAGE\" &&
            export ADMIN_USERNAME=\"$ADMIN_USERNAME\" &&
            export ADMIN_PASSWORD=\"$ADMIN_PASSWORD\" &&
            export REAL_ESTATE_API_KEY=\"$REAL_ESTATE_API_KEY\" &&
            export JWT_SECRET=\"$JWT_SECRET\" &&
            export REDIS_HOST=\"$REDIS_HOST\" &&
            export MONGODB_URI=\"$MONGODB_URI\" &&
            export PROXY_API_KEY=\"$PROXY_API_KEY\" &&
            export TWO_CAPTCHA_API_KEY=\"$TWO_CAPTCHA_API_KEY\" &&
            export CAPSOLVER_API_KEY=\"$CAPSOLVER_API_KEY\" &&
            export SHIFTER_API_KEY=\"$SHIFTER_API_KEY\" &&
            docker compose -f /home/haythem/compose.prod.yml down &&
            docker image prune -f &&
            docker compose -f /home/haythem/compose.prod.yml up -d"
    
