stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  SERVER_IMAGE: $CI_REGISTRY_IMAGE/real-estate-server
  DASHBOARD_IMAGE: $CI_REGISTRY_IMAGE/real-estate-dashboard

build_server:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd real-estate-server
    - docker build -t $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA $SERVER_IMAGE:latest
    - docker push $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $SERVER_IMAGE:latest

build_dashboard:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd real-estate-dashboard
  script:
    - docker build -t $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA $DASHBOARD_IMAGE:latest
    - docker push $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DASHBOARD_IMAGE:latest

deploy:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  environment:
    name: production
    url: https://$SERVER_IP
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SERVER_IP" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh haythem@$SERVER_IP "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
    - ssh haythem@$SERVER_IP "docker pull $SERVER_IMAGE:latest"
    - ssh haythem@$SERVER_IP "docker pull $DASHBOARD_IMAGE:latest"
    - ssh haythem@$SERVER_IP "docker-compose down && docker-compose up -d"
