stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  SERVER_IMAGE: $CI_REGISTRY_IMAGE/real-estate-server
  DASHBOARD_IMAGE: $CI_REGISTRY_IMAGE/real-estate-dashboard

build_server:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd real-estate-server
    - docker build -t $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA $SERVER_IMAGE:latest
    - docker push $SERVER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $SERVER_IMAGE:latest

build_dashboard:
  stage: build
  image: docker:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd real-estate-dashboard
  script:
    - docker build -t $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA $DASHBOARD_IMAGE:latest
    - docker push $DASHBOARD_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DASHBOARD_IMAGE:latest

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == "main"
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $SERVER_IMAGE:latest"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $DASHBOARD_IMAGE:latest"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose down && docker-compose up -d"
