stages:
  - build
  - test
  - deploy

build_server:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - cd real-estate-server
    - docker build -t $CI_REGISTRY_IMAGE/real-estate-server:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE/real-estate-server:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/real-estate-server:latest
    - docker push $CI_REGISTRY_IMAGE/real-estate-server:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/real-estate-server:latest

build_dashboard:
  stage: build
  script:
    - cd real-estate-dashboard
    - docker build -t $CI_REGISTRY_IMAGE/real-estate-dashboard:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE/real-estate-dashboard:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/real-estate-dashboard:latest
    - docker push $CI_REGISTRY_IMAGE/real-estate-dashboard:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/real-estate-dashboard:latest

deploy:
  stage: deploy
  script:
    - echo "$KUBE_CONFIG" | base64 -d > $KUBECONFIG
    - kubectl --kubeconfig=$KUBECONFIG apply -f kubernetes/deployment.yaml
    - kubectl --kubeconfig=$KUBECONFIG apply -f kubernetes/service.yaml
  only:
    - main
