
services:
  redis:
    image: redis:7.2.5
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./local-data/redis_data:/data

  mongodb:
    image: mongo:5.0.28
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./local-data/mongd_data:/data/db