apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: $CI_REGISTRY_IMAGE/real-estate-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/mydb"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 3000
  selector:
    app: backend
