services:
  mongodb:
    image: mongo:5.0.28
    container_name: mongodb-container
    restart: on-failure
    env_file:
      - ./environments/production.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - type: bind
        source: ./bin
        target: /docker-entrypoint-initdb.d/

  backend:
    image: ${BACKEND_IMAGE}:latest
    container_name: real-estate-server-container
    restart: on-failure
    expose:
      - 3000
    ports:
      - "3000:3000"
    env_file:
      - ./environments/production.env
    depends_on:
      - mongodb

  frontend:
    image: ${DASHBOARD_IMAGE}:latest
    container_name: frontend-container
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - backend
      

volumes:
  mongo_data:
    external: true