services:
  mongodb:
    image: mongo:5.0.28
    container_name: mongodb-container
    restart: on-failure
    env_file:
      - ./environments/production.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - type: bind
        source: ./bin
        target: /docker-entrypoint-initdb.d/

  backend:
    image: ${BACKEND_IMAGE}:latest
    container_name: real-estate-server-container
    restart: on-failure
    expose:
      - 3000
    env_file:
      - ./environments/production.env
    depends_on:
      - mongodb

  frontend:
    image: ${DASHBOARD_IMAGE}:latest
    container_name: frontend-container
    restart: on-failure
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    container_name: nginx_prod
    ports:
      - "443:443"
      - "80:80"
      - "3000:3000"
    volumes:
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /home/haythem/real-estate-backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
    external: true
  frontend_data:
